SITENAME = "Cats and Dogs"
SITEAUTHOR = "Cebolinha"
SITELANGUAGE = "en"
SITEURL = "www.catsandogs.com"
SITETIMEZONE = "America/Sao_Paulo"

THEME = "sagu"
BASETEMPLATE = "index.jinja"
STATIC = "static"

MENUITEMS = [
{ title = "Akita", link = "the-noble-akita"},
{ title = "Donskoy", link = "donskoy"}
]

